---
- name: Setup Bamboo server
  hosts: bamboo_master 
  become: yes
  become_method: sudo
  become_user: root    
  #  gather_facts: no
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
    bamboo_url: https://www.atlassian.com/software/bamboo/downloads/binary/atlassian-bamboo-9.0.0.tar.gz
    bamboo_home: /var/bamboo/bamboo_home
    bamboo_install: /opt/bamboo
    paths:
       - /tmp/bamboo9
       - /var/bamboo/bamboo_home
       - /opt/bamboo

  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - openjdk-8-jdk
          - maven
          - postgresql
          - postgresql-contrib
          
    - name: Download Tomcat Tar Ball/Binaries
      get_url:
        url: "{{bamboo_url}}"
        dest: /tmp/bamboo-9.tar.gz

    - name: Add bamboo group
      group:
        name: bamboo
        state: present

    - name: Add bamboo user
      user:
        name: bamboo
        group: bamboo
        shell: /bin/nologin
        home: /usr/local/bamboo

    - file:
        path: /opt/bamboo
        state: directory
    - file:
        path: /tmp/bamboo9
        state: directory
    - file:
        path: /var/bamboo/bamboo_home
        state: directory
   
    - name: Extract bamboo
      unarchive:
        src: /tmp/bamboo-9.tar.gz
        dest: /tmp/bamboo9/
        remote_src: yes
        list_files: yes
      register: unarchive_info

    - debug:
        msg: "{{unarchive_info.files[0].split('/')[0]}}"

    - name: Synchronize /tmp/bamboo /opt/bamboo
      synchronize:
        src: "/tmp/bamboo9/{{unarchive_info.files[0].split('/')[0]}}/"
        dest: /opt/bamboo/
      delegate_to: "{{ inventory_hostname }}"

    - name: Change ownership of /opt/bamboo
      file:
        path: /opt/bamboo
        owner: bamboo
        group: bamboo
        recurse: yes
    
    - name: Set Bamboo home directory 
      ansible.builtin.lineinfile:
        path: '{{ bamboo_install }}/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties'
        regexp: '#bamboo.home=C:/bamboo/bamboo-home'
        line: bamboo.shared.home={{ bamboo_home }}

    - name: Setup bamboo SVC file on ubuntu 20
      template:
        src: templates/bamboo9-ubuntu-svcfile.j2
        dest: /etc/systemd/system/bamboo.service
        mode: "a+x"

    - name: just force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes

    - name: Start & Enable bambo SVC
      service:
        name: bamboo
        state: started
        enabled: yes
      tags:
        - svc
    

